name: Hank Quinlan, Horrible Cop
markdown: kramdown
<<<<<<< HEAD
permalink: /blog/:year/:month/:day/:title
=======
permalink: "/blog/:year/:month/:day/:title"
Field name: 

theme: jekyll-theme-minimal
>>>>>>> cf809a396e6d6d8dd152c45f0933b19e49facfd3
