title: Curious Programmer
description: Showcasing my talent
author: Sarah Bolt
logo: /static/img/avatar.png
github: https://github.com/sdf94
about: Switching careers from Chemistry to Data analysis. 

baseurl: "https://sdf94.github.io"
url: "https://sdf94.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
