---
title: Sdf94.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Sarah Floris
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
Field name: 

theme: jekyll-theme-minimal